package com.network.social.domain.util.form;
// Generated 10/10/2015 01:01:29 AM by Hibernate Tools 4.3.1.Final

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "COMENTARIO")
public class ComentarioForm extends BaseForm {
	private static final long serialVersionUID = 1L;

	private Integer idcomentario;
	private MultimediaForm multimedia;
	private PublicacionForm publicacion;
	private AlbumForm album;
	private UsuarioForm usuario;
	private Clob contenido;
	private Date fechaComentario;
	private Integer likes;
	private Set<EtiquetaForm> etiquetas = new HashSet<EtiquetaForm>();
	private Set<NotificacionForm> notificacioneses = new HashSet<NotificacionForm>();
	private Set<LikeForm> likes_1 = new HashSet<LikeForm>();
	private Set<ActividadForm> actividads = new HashSet<ActividadForm>();

	public ComentarioForm() {
	}

	public ComentarioForm(Integer idcomentario, UsuarioForm usuario) {
		this.idcomentario = idcomentario;
		this.usuario = usuario;
	}

	public ComentarioForm(Integer idcomentario, MultimediaForm multimedia, PublicacionForm publicacion, AlbumForm album,
			UsuarioForm usuario, Clob contenido, Date fechaComentario, Integer likes, Set<EtiquetaForm> etiquetas,
			Set<NotificacionForm> notificacioneses, Set<LikeForm> likes_1, Set<ActividadForm> actividads) {
		this.idcomentario = idcomentario;
		this.multimedia = multimedia;
		this.publicacion = publicacion;
		this.album = album;
		this.usuario = usuario;
		this.contenido = contenido;
		this.fechaComentario = fechaComentario;
		this.likes = likes;
		this.etiquetas = etiquetas;
		this.notificacioneses = notificacioneses;
		this.likes_1 = likes_1;
		this.actividads = actividads;
	}

	@Id

	@Column(name = "IDCOMENTARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdcomentario() {
		return this.idcomentario;
	}

	public void setIdcomentario(Integer idcomentario) {
		this.idcomentario = idcomentario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMULTIMEDIA")
	public MultimediaForm getMultimedia() {
		return this.multimedia;
	}

	public void setMultimedia(MultimediaForm multimedia) {
		this.multimedia = multimedia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPUBLICACION")
	public PublicacionForm getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(PublicacionForm publicacion) {
		this.publicacion = publicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDALBUM")
	public AlbumForm getAlbum() {
		return this.album;
	}

	public void setAlbum(AlbumForm album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO", nullable = false)
	public UsuarioForm getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioForm usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CONTENIDO")
	public Clob getContenido() {
		return this.contenido;
	}

	public void setContenido(Clob contenido) {
		this.contenido = contenido;
	}

	@Column(name = "FECHA_COMENTARIO")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getFechaComentario() {
		return this.fechaComentario;
	}

	public void setFechaComentario(Date fechaComentario) {
		this.fechaComentario = fechaComentario;
	}

	@Column(name = "LIKES", precision = 22, scale = 0)
	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<EtiquetaForm> getEtiquetas() {
		return this.etiquetas;
	}

	public void setEtiquetas(Set<EtiquetaForm> etiquetas) {
		this.etiquetas = etiquetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<NotificacionForm> getNotificacioneses() {
		return this.notificacioneses;
	}

	public void setNotificacioneses(Set<NotificacionForm> notificacioneses) {
		this.notificacioneses = notificacioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<LikeForm> getLikes_1() {
		return this.likes_1;
	}

	public void setLikes_1(Set<LikeForm> likes_1) {
		this.likes_1 = likes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<ActividadForm> getActividads() {
		return this.actividads;
	}

	public void setActividads(Set<ActividadForm> actividads) {
		this.actividads = actividads;
	}

}
