package com.network.social.domain.entities;
// Generated 10/10/2015 01:01:29 AM by Hibernate Tools 4.3.1.Final

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "COMENTARIO")
public class Comentario extends BaseBean {
	private static final long serialVersionUID = 1L;

	private Integer idcomentario;
	private Multimedia multimedia;
	private Publicacion publicacion;
	private Album album;
	private Usuario usuario;
	private Clob contenido;
	private Date fechaComentario;
	private Integer likes;
	private Set<Etiqueta> etiquetas = new HashSet<Etiqueta>();
	private Set<Notificacion> notificacioneses = new HashSet<Notificacion>();
	private Set<Like> likes_1 = new HashSet<Like>();
	private Set<Actividad> actividads = new HashSet<Actividad>();

	public Comentario() {
	}

	public Comentario(Integer idcomentario, Usuario usuario) {
		this.idcomentario = idcomentario;
		this.usuario = usuario;
	}

	public Comentario(Integer idcomentario, Multimedia multimedia, Publicacion publicacion, Album album,
			Usuario usuario, Clob contenido, Date fechaComentario, Integer likes, Set<Etiqueta> etiquetas,
			Set<Notificacion> notificacioneses, Set<Like> likes_1, Set<Actividad> actividads) {
		this.idcomentario = idcomentario;
		this.multimedia = multimedia;
		this.publicacion = publicacion;
		this.album = album;
		this.usuario = usuario;
		this.contenido = contenido;
		this.fechaComentario = fechaComentario;
		this.likes = likes;
		this.etiquetas = etiquetas;
		this.notificacioneses = notificacioneses;
		this.likes_1 = likes_1;
		this.actividads = actividads;
	}

	@Id

	@Column(name = "IDCOMENTARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdcomentario() {
		return this.idcomentario;
	}

	public void setIdcomentario(Integer idcomentario) {
		this.idcomentario = idcomentario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMULTIMEDIA")
	public Multimedia getMultimedia() {
		return this.multimedia;
	}

	public void setMultimedia(Multimedia multimedia) {
		this.multimedia = multimedia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPUBLICACION")
	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDALBUM")
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CONTENIDO")
	public Clob getContenido() {
		return this.contenido;
	}

	public void setContenido(Clob contenido) {
		this.contenido = contenido;
	}

	@Column(name = "FECHA_COMENTARIO")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getFechaComentario() {
		return this.fechaComentario;
	}

	public void setFechaComentario(Date fechaComentario) {
		this.fechaComentario = fechaComentario;
	}

	@Column(name = "LIKES", precision = 22, scale = 0)
	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<Etiqueta> getEtiquetas() {
		return this.etiquetas;
	}

	public void setEtiquetas(Set<Etiqueta> etiquetas) {
		this.etiquetas = etiquetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<Notificacion> getNotificacioneses() {
		return this.notificacioneses;
	}

	public void setNotificacioneses(Set<Notificacion> notificacioneses) {
		this.notificacioneses = notificacioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<Like> getLikes_1() {
		return this.likes_1;
	}

	public void setLikes_1(Set<Like> likes_1) {
		this.likes_1 = likes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comentario")
	public Set<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(Set<Actividad> actividads) {
		this.actividads = actividads;
	}

}
