package com.network.social.domain.entities;
// Generated 10/10/2015 01:01:29 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name = "IDIOMA")
public class Idioma extends BaseBean {
	private static final long serialVersionUID = 1L;

	private Integer ididioma;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>();

	public Idioma() {
	}

	public Idioma(Integer ididioma) {
		this.ididioma = ididioma;
	}

	public Idioma(Integer ididioma, String nombre, Set<Usuario> usuarios) {
		this.ididioma = ididioma;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "IDIDIOMA", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdidioma() {
		return this.ididioma;
	}

	public void setIdidioma(Integer ididioma) {
		this.ididioma = ididioma;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USUARIO_IDIOMA", joinColumns = {
			@JoinColumn(name = "IDIDIOMA", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDUSUARIO", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
