package com.network.social.domain.entities;


import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Multimedia generated by hbm2java
 */
@Entity
@Table(name = "MULTIMEDIA")
public class Multimedia extends BaseBean {
	private static final long serialVersionUID = 1L;

	private Integer idmultimedia;
	private Publicacion publicacion;
	private Album album;
	private ListaContacto listaContactos;
	private TipoContacto tipoContacto;
	private String nombreArchivo;
	private Clob descripcion;
	private Integer tipo;
	private Integer likes;
	private Set<Comentario> comentarios = new HashSet<Comentario>();
	private Set<Like> likes_1 = new HashSet<Like>();
	private Set<Etiqueta> etiquetas = new HashSet<Etiqueta>();

	public Multimedia() {
	}

	public Multimedia(Integer idmultimedia, Publicacion publicacion, Album album, String nombreArchivo) {
		this.idmultimedia = idmultimedia;
		this.publicacion = publicacion;
		this.album = album;
		this.nombreArchivo = nombreArchivo;
	}

	public Multimedia(Integer idmultimedia, Publicacion publicacion, Album album, ListaContacto listaContactos,
			TipoContacto tipoContacto, String nombreArchivo, Clob descripcion, Integer tipo, Integer likes,
			Set<Comentario> comentarios, Set<Like> likes_1, Set<Etiqueta> etiquetas) {
		this.idmultimedia = idmultimedia;
		this.publicacion = publicacion;
		this.album = album;
		this.listaContactos = listaContactos;
		this.tipoContacto = tipoContacto;
		this.nombreArchivo = nombreArchivo;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.likes = likes;
		this.comentarios = comentarios;
		this.likes_1 = likes_1;
		this.etiquetas = etiquetas;
	}

	@Id

	@Column(name = "IDMULTIMEDIA", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdmultimedia() {
		return this.idmultimedia;
	}

	public void setIdmultimedia(Integer idmultimedia) {
		this.idmultimedia = idmultimedia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPUBLICACION", nullable = false)
	public Publicacion getPublicacion() {
		return this.publicacion;
	}

	public void setPublicacion(Publicacion publicacion) {
		this.publicacion = publicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDALBUM", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDLISTA_CONTACTOS")
	public ListaContacto getListaContactos() {
		return this.listaContactos;
	}

	public void setListaContactos(ListaContacto listaContactos) {
		this.listaContactos = listaContactos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTIPO_CONTACTO")
	public TipoContacto getTipoContacto() {
		return this.tipoContacto;
	}

	public void setTipoContacto(TipoContacto tipoContacto) {
		this.tipoContacto = tipoContacto;
	}

	@Column(name = "NOMBRE_ARCHIVO", nullable = false, length = 200)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	@Column(name = "DESCRIPCION")
	public Clob getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Clob descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "TIPO", precision = 22, scale = 0)
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "LIKES", precision = 22, scale = 0)
	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimedia")
	public Set<Comentario> getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(Set<Comentario> comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimedia")
	public Set<Like> getLikes_1() {
		return this.likes_1;
	}

	public void setLikes_1(Set<Like> likes_1) {
		this.likes_1 = likes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimedia")
	public Set<Etiqueta> getEtiquetas() {
		return this.etiquetas;
	}

	public void setEtiquetas(Set<Etiqueta> etiquetas) {
		this.etiquetas = etiquetas;
	}

}
