package com.network.social.domain.entities;
// Generated 10/10/2015 01:01:29 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContacto generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CONTACTO")
public class TipoContacto extends BaseBean {
	private static final long serialVersionUID = 1L;

	private Integer idtipoContacto;
	private String nombre;
	private Set<Multimedia> multimedias = new HashSet<Multimedia>();
	private Set<Contacto> contactos = new HashSet<Contacto>();
	private Set<Publicacion> publicacions = new HashSet<Publicacion>();

	public TipoContacto() {
	}

	public TipoContacto(Integer idtipoContacto) {
		this.idtipoContacto = idtipoContacto;
	}

	public TipoContacto(Integer idtipoContacto, String nombre, Set<Multimedia> multimedias, Set<Contacto> contactos,
			Set<Publicacion> publicacions) {
		this.idtipoContacto = idtipoContacto;
		this.nombre = nombre;
		this.multimedias = multimedias;
		this.contactos = contactos;
		this.publicacions = publicacions;
	}

	@Id

	@Column(name = "IDTIPO_CONTACTO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdtipoContacto() {
		return this.idtipoContacto;
	}

	public void setIdtipoContacto(Integer idtipoContacto) {
		this.idtipoContacto = idtipoContacto;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Multimedia> getMultimedias() {
		return this.multimedias;
	}

	public void setMultimedias(Set<Multimedia> multimedias) {
		this.multimedias = multimedias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
